name: Dev CI

on:
  push:
    branches: [master, pr/fixes-listing-misc]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Write File
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: '.env.local'
          contents: 'REACT_APP_API_ENDPOINT=http://api.staging.control.cov2.in/api/'
          write-mode: 'overwrite'

      - name: Read file
        run: cat .env.local

      - name: list files
        run: ls -l

      - name: Yarn Install Dependencies
        uses: CultureHQ/actions-yarn@v1.0.1
        with:
          args: install

      - name: npm run build
        run: npm run build

      - name: Log npm errors
        if: failure()
        run: cat /home/runner/.npm/_logs/*

      - name: List build directory
        run: ls -R build/

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: 'control.covid-dev'
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}
          AWS_REGION: 'ap-south-1'
          SOURCE_DIR: 'build'
          DEST_DIR: 'build'

      - name: Invalidate cache
        uses: chetan/invalidate-cloudfront-action@v1.2
        env:
          DISTRIBUTION: ${{ secrets.cloudfront_dist_dev }}
          PATHS: '/*'
          AWS_REGION: 'ap-south-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}
